/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.hotel;

import bkap.daoimpl.RoleGroupDaoImpl;
import bkap.utils.Constant;
import bkap.utils.Helper;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admi
 */
public class DangNhap extends javax.swing.JDialog {
    boolean checkDN = false;
    String username;
    Helper helper;
    RoleGroupDaoImpl roleGroupDaoImpl;
    int level;
    /**
     * Creates new form DangNhap
     */
    public DangNhap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        helper = new Helper();
        roleGroupDaoImpl = new RoleGroupDaoImpl();
        helper.validateFieldInPanel(pThongTinDn);
//        loadData();
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }
    
    
//    public void loadData() {
//        helper.loadDataIntoComboBox(cboRole, Constant.SQL_ALL_ROLES, "Id_group_role");
//    }

    public boolean isCheckDN() {
        return checkDN;
    }

    public void setCheckDN(boolean checkDN) {
        this.checkDN = checkDN;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pThongTinDn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btnThoat = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/icon/login-1.png"))); // NOI18N

        pThongTinDn.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đăng nhập"));

        jLabel2.setText("Tên đăng nhập: ");

        jLabel3.setText("Mật khẩu:");

        javax.swing.GroupLayout pThongTinDnLayout = new javax.swing.GroupLayout(pThongTinDn);
        pThongTinDn.setLayout(pThongTinDnLayout);
        pThongTinDnLayout.setHorizontalGroup(
            pThongTinDnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongTinDnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pThongTinDnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongTinDnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenDN)
                    .addComponent(txtMatKhau))
                .addContainerGap())
        );
        pThongTinDnLayout.setVerticalGroup(
            pThongTinDnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongTinDnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pThongTinDnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pThongTinDnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnThoat.setText("Thoát");

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        lblStatus.setText("__");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pThongTinDn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 123, Short.MAX_VALUE)
                                .addComponent(btnDangNhap)
                                .addGap(18, 18, 18)
                                .addComponent(btnThoat)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblStatus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pThongTinDn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnDangNhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
//        try {
//        if(cboRole.getSelectedItem().equals("MANAGER")) {
//            if(helper.checkFormValid(pThongTinDn)) {
//                    System.out.println("bkap.hotel.DangNhap.btnDangNhapActionPerformed()"+helper.checkUser(1, txtTenDN.getText(), txtMatKhau.getText()));
//                    if(helper.checkUser(1, txtTenDN.getText(), txtMatKhau.getText())){
//                        checkDN = true;
//                        setLevel(1);
//                        dispose();
//                    } else {
//                        lblStatus.setText("Tên đăng nhập/mật khẩu sai");
//                        lblStatus.setForeground(Color.red);
//                    }
//                
//                }else{
//                    helper.messageNullValuesForForm(pThongTinDn);
//                }
//            }else if(cboRole.getSelectedIndex() == 2){
//                System.out.println("ADMIN");
//                if (helper.checkFormValid(pThongTinDn)) {
//                    if (helper.checkUser(2, txtTenDN.getText(), txtMatKhau.getText())) {
//                        checkDN = true;
//                        dispose();
//                    } else {
//                        lblStatus.setText("Tên đăng nhập/mật khẩu sai");
//                        lblStatus.setForeground(Color.red);
//                    }
//                    System.out.println(checkDN);
//                } else {
//                    helper.messageNullValuesForForm(pThongTinDn);
//                }
//            }
//        
//        } catch (SQLException ex) {
//                    Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
//        } 

        int role_group = 0;
        try {
            role_group = helper.checkUser(txtTenDN.getText(), txtMatKhau.getText());
            if(role_group > 0) {
                checkDN = true;
                setLevel(role_group);
                dispose();
            }else{
                checkDN = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pThongTinDn;
    public static javax.swing.JPasswordField txtMatKhau;
    public static javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
