/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.internalframe;

import bkap.daoimpl.DepartmentDaoImpl;
import bkap.utils.Helper;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import bkap.entity.Department;
import bkap.utils.Constant;
import bkap.utils.DialogThongBao;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author admi
 */
public class Department_JIF extends javax.swing.JInternalFrame {
    DefaultTableModel dtm;
    Helper helper;
    DepartmentDaoImpl departmentDaoImpl;
    List<Department> lstDepartment;
    private int pos = -1;
    /**
     * Creates new form Department
     */
    public Department_JIF() {
        initComponents();
        loadData();
        btnCapNhat.setEnabled(false);
        btnXoa.setEnabled(false);
    }
    
    private void loadData() {
        helper = new Helper();
        departmentDaoImpl = new DepartmentDaoImpl();
        loadTableDepartment();
    }
    
    public void loadTableDepartment() {
        String columnsName[] = {
            "Id", "Name", "NameSub", "Note"
        };
        dtm = new DefaultTableModel(columnsName, 0);
        dtm.getDataVector().removeAllElements();
        lstDepartment = departmentDaoImpl.getAllDepartment();
        for (int i = 0; i < lstDepartment.size(); i++) {
            Department d = lstDepartment.get(i);
            Vector row = new Vector();
            row.add(d.getId());
            row.add(d.getId_department());
            row.add(d.getName());
            row.add(d.getNote());
            dtm.addRow(row);
        }
        tblDepartment.setModel(dtm);
        
        tblDepartment.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                btnThemMoi.setEnabled(false);
                btnCapNhat.setEnabled(true);
                btnXoa.setEnabled(true);
                if(tblDepartment.getSelectedRow() >= 0 && tblDepartment.getSelectedRow() <lstDepartment.size()){
                    pos = tblDepartment.getSelectedRow();
                    lblId.setText(String.valueOf(lstDepartment.get(pos).getId()));
                    txtNameSub.setText(lstDepartment.get(pos).getId_department());
                    txtName.setText(lstDepartment.get(pos).getName());
                    teaNote.setText(lstDepartment.get(pos).getNote());
                }
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPhongBan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNameSub = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teaNote = new javax.swing.JTextArea();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDepartment = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        formPhongBan.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Phòng Ban"));

        jLabel1.setText("Id:");

        jLabel2.setText("Mã Viết Tắt: ");

        jLabel3.setText("Tên phòng ban:");

        jLabel4.setText("Ghi Chú:");

        teaNote.setColumns(20);
        teaNote.setRows(5);
        jScrollPane1.setViewportView(teaNote);

        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/icon/add_.png"))); // NOI18N
        btnThemMoi.setText("Thêm Mới");
        btnThemMoi.setPreferredSize(new java.awt.Dimension(100, 30));
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/icon/edit.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(100, 30));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lblId.setText("...");

        javax.swing.GroupLayout formPhongBanLayout = new javax.swing.GroupLayout(formPhongBan);
        formPhongBan.setLayout(formPhongBanLayout);
        formPhongBanLayout.setHorizontalGroup(
            formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPhongBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPhongBanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPhongBanLayout.createSequentialGroup()
                        .addGroup(formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameSub)
                            .addComponent(txtName)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                            .addGroup(formPhongBanLayout.createSequentialGroup()
                                .addComponent(lblId)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        formPhongBanLayout.setVerticalGroup(
            formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPhongBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblId))
                .addGap(18, 18, 18)
                .addGroup(formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNameSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 25, Short.MAX_VALUE)
                .addGroup(formPhongBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDepartment);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formPhongBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String name,nameSub,note;
    int id;
    private void prepareData() {
        if(lblId.getText() == "...") {
            id = 0;
        }else{
            id = Integer.parseInt(lblId.getText());
        }
        nameSub = txtNameSub.getText();
        name = txtName.getText();
        note = teaNote.getText();
    }
    
    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        if(helper.checkFormValid(formPhongBan)){
            prepareData();
            departmentDaoImpl = new DepartmentDaoImpl();
            Department d = new Department(nameSub, name, note);
            int kq = departmentDaoImpl.insert(d);
            if(kq > 0) {
                DialogThongBao.showSuccess(this, Constant.MSG_SUCCESS_INSERT_USERS, Constant.MSG_SUCCESS_INSERT_USERS);
            }
            clearInput();
            loadData();
        }else{
            helper.messageNullValuesForForm(formPhongBan);
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        
        if(helper.checkFormValid(formPhongBan)) {
            prepareData();
            Department d = new Department(id, nameSub, name, note);
            int kq = departmentDaoImpl.update(d);
            if(kq > 0) {
                DialogThongBao.showSuccess(this, Constant.MSG_SUCCESS_UPDATE, Constant.MSG_SUCCESS_UPDATE);
            }
            loadData();
            clearInput();
            btnCapNhat.setEnabled(false);
            btnThemMoi.setEnabled(true);
            btnXoa.setEnabled(false);
        }else{
            helper.messageNullValuesForForm(formPhongBan);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(DialogThongBao.showAlert(this, Constant.MSG_XAC_NHAN_XOA, txtName.getText()) == JOptionPane.OK_OPTION){
            departmentDaoImpl = new DepartmentDaoImpl();
            if(departmentDaoImpl.delete(Integer.parseInt(lblId.getText())) > 0) {
                lstDepartment.remove(pos);
                dtm.removeRow(pos);
                dtm.fireTableDataChanged();
                clearInput();
                btnCapNhat.setEnabled(false);
                btnThemMoi.setEnabled(true);
                btnXoa.setEnabled(false);
            }else{
                DialogThongBao.showError(this, Constant.MSG_SUCCESS_DELETE , Constant.MSG_SUCCESS_DELETE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    public void clearInput() {
        lblId.setText("...");
        txtNameSub.setText(null);
        txtName.setText(null);
        teaNote.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel formPhongBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tblDepartment;
    private javax.swing.JTextArea teaNote;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameSub;
    // End of variables declaration//GEN-END:variables
}
