/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.internalframe;

import bkap.daoimpl.UserDaoImpl;
import bkap.utils.Constant;
import bkap.utils.DialogThongBao;
import bkap.utils.Helper;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admi
 */
public class DoiMatKhau extends javax.swing.JInternalFrame {
    Helper dbHelper;
    UserDaoImpl daoImpl ;
    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
        dbHelper = new Helper();
        daoImpl = new UserDaoImpl();
        dbHelper.validateFieldInPanel(pDoiMK);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDoiMK = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMatKhauCu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtXacNhanMK = new javax.swing.JPasswordField();
        btnThayDoi = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        LbXNMatKhauCu = new javax.swing.JLabel();
        txtMatKhauMoi = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Đổi mật khẩu");

        pDoiMK.setBorder(javax.swing.BorderFactory.createTitledBorder("Đổi mật khẩu"));

        jLabel1.setText("Mật khẩu cũ:");

        txtMatKhauCu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatKhauCuKeyReleased(evt);
            }
        });

        jLabel2.setText("Mật khẩu mới: ");

        jLabel3.setText("Xác nhận mk:");

        btnThayDoi.setText("Thay đổi");
        btnThayDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThayDoiActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDoiMKLayout = new javax.swing.GroupLayout(pDoiMK);
        pDoiMK.setLayout(pDoiMKLayout);
        pDoiMKLayout.setHorizontalGroup(
            pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDoiMKLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDoiMKLayout.createSequentialGroup()
                        .addComponent(btnThayDoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnHuy)
                        .addContainerGap(179, Short.MAX_VALUE))
                    .addGroup(pDoiMKLayout.createSequentialGroup()
                        .addGroup(pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMatKhauCu)
                            .addComponent(txtXacNhanMK, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbXNMatKhauCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pDoiMKLayout.setVerticalGroup(
            pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LbXNMatKhauCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtXacNhanMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThayDoi)
                    .addComponent(btnHuy))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThayDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThayDoiActionPerformed
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("/bkap/icon/enable.png"));
        String mkMoi = txtMatKhauMoi.getText();
        String xnMkMoi = txtXacNhanMK.getText();
        
        if(dbHelper.checkFormValid(pDoiMK)) {
            if(mkMoi.equals(xnMkMoi)) {
                System.out.println("Đổi mật khẩu thành công");
                int kq = daoImpl.doiMatKhau(mkMoi,DangNhap.txtTaiKhoan.getText());
                if(kq > 0) {
                    DialogThongBao.showSuccess(this, Constant.MSG_THONG_BAO_DANG_NHAP, Constant.MSG_SUCCESS_PASSWORD);
                }else{
                    DialogThongBao.showError(this, Constant.MSG_THONG_BAO_DANG_NHAP, Constant.MSG_ERROR_PASSWORD);
                }
            }else if(LbXNMatKhauCu.getIcon().equals(img)){
                DialogThongBao.showError(this, Constant.MSG_THONG_BAO_DANG_NHAP, Constant.MSG_ERROR_PASSWORD);
            }
        }else {
            dbHelper.messageNullValuesForForm(pDoiMK);
        }
    }//GEN-LAST:event_btnThayDoiActionPerformed

    private void txtMatKhauCuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauCuKeyReleased
        // TODO add your handling code here:
         if (txtMatKhauCu.getText().equals(DangNhap.txtpass.getText())) {
            LbXNMatKhauCu.setIcon(new ImageIcon(getClass().getResource("/bkap/icon/enable.png")));
            LbXNMatKhauCu.setText(null);
        } else {
            LbXNMatKhauCu.setText("Mk không đúng");
            LbXNMatKhauCu.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtMatKhauCuKeyReleased

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbXNMatKhauCu;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThayDoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pDoiMK;
    private javax.swing.JTextField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtXacNhanMK;
    // End of variables declaration//GEN-END:variables
}
