/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.internalframe;

import bkap.daoimpl.ServiceDaoImp;
import bkap.entity.Service;
import bkap.utils.Constant;
import bkap.utils.DialogThongBao;
import bkap.utils.Helper;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.border.LineBorder;

/**
 *
 * @author ADMIN
 */
public class Service_JIF extends javax.swing.JInternalFrame {
    private Helper hp = new Helper();
    /**
     * Creates new form Service_JInternalFrame
     */
    public Service_JIF() {
        initComponents();
        config_basic();
        loadTable();
    }
    public void config_basic(){
        txtId.setVisible(false);
        btn_delete.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
    }
    public int checkValidate(){
        int checkValidate=0;
        //        Validate 
        if (txtName.getText().trim().length()==0) {
            checkValidate++;
            txtErrorName.setText("Name not empty!");
        }else{
            txtErrorName.setText("");
        }
        try {
            Float price = Float.parseFloat(txtPrice.getText());
            txtErrorPrice.setText("");
        } catch (NumberFormatException e) {
            checkValidate++;
            txtErrorPrice.setText("Price must number!");
        }
        return checkValidate;
    }
    public void loadTable(){
        String[] colums = {"Id","Name","Price","Date Created"};
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.setColumnIdentifiers(colums);
        ServiceDaoImp serviceDaoImp = new ServiceDaoImp();
        List<Service> ls =  serviceDaoImp.getAllService();
        for (Service l : ls) {
            defaultTableModel.addRow(new Object[]{
                l.getId(),
                l.getName(),
                l.getPrice(),
                l.getDateCreated()
            });
        }
        table_dataSerice.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dataSerice = new javax.swing.JTable();
        formData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtErrorName = new javax.swing.JLabel();
        txtErrorPrice = new javax.swing.JLabel();
        btn_loadData = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Service");

        table_dataSerice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_dataSerice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dataSericeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_dataSerice);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        formData.setBorder(javax.swing.BorderFactory.createTitledBorder("Service Information"));

        jLabel1.setText("Name:");

        jLabel2.setText("Price:");

        txtErrorName.setForeground(new java.awt.Color(255, 0, 51));

        txtErrorPrice.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout formDataLayout = new javax.swing.GroupLayout(formData);
        formData.setLayout(formDataLayout);
        formDataLayout.setHorizontalGroup(
            formDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(formDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtErrorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formDataLayout.createSequentialGroup()
                        .addGroup(formDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtErrorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formDataLayout.setVerticalGroup(
            formDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(formDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(formDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorPrice)
                .addGap(8, 8, 8))
        );

        btn_loadData.setText("Load Data");
        btn_loadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadDataActionPerformed(evt);
            }
        });

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/icon/edit.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/icon/add_.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/icon/delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/icon/eraser.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_loadData, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(formData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_loadData, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadDataActionPerformed
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_btn_loadDataActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:  
        if (checkValidate()==0) {
            ServiceDaoImp serviceDaoImp = new ServiceDaoImp();
            Service service_entity = new Service(Integer.parseInt(txtId.getText()),txtName.getText(), Float.parseFloat(txtPrice.getText()));
            if (serviceDaoImp.update(service_entity)!=0) {
                DialogThongBao.showSuccess(this, "Alert", "Update data success");
                loadTable();
                btn_delete.setEnabled(false);
            }else{
                DialogThongBao.showError(this, "Alert", "Update data error!");
            }
        }
       
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if (checkValidate()==0) {
            ServiceDaoImp serviceDaoImp = new ServiceDaoImp();
            Service service_entity = new Service(txtName.getText(), Float.parseFloat(txtPrice.getText()));
            if (serviceDaoImp.insert(service_entity)!=0) {
                DialogThongBao.showSuccess(this, "Alert", "Insert data success");
                loadTable();
            }else{
                 DialogThongBao.showError(this, "Alert", "Insert data success");
            }
        }
        
            
      
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (DialogThongBao.showAlert(this, "Alert", "Do you want to delete?")==0) {
            ServiceDaoImp serviceDaoImp = new ServiceDaoImp();
            serviceDaoImp.delete(Integer.parseInt(txtId.getText()));
            loadTable();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void table_dataSericeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dataSericeMouseClicked
        // TODO add your handling code here:
        int row = table_dataSerice.getSelectedRow();
        int id = (int) table_dataSerice.getValueAt(row,0);
//        Call class 
        ServiceDaoImp serviceDaoImp = new ServiceDaoImp();
        Service service_entity = serviceDaoImp.getServiceById(id);
//        Xet gia tri 
        txtName.setText(service_entity.getName());
        txtPrice.setText(String.valueOf(service_entity.getPrice()));
        txtId.setText(String.valueOf(service_entity.getId()));
//        set btn 
        btn_add.setEnabled(false);
        btn_delete.setEnabled(true);
        btn_edit.setEnabled(true);
        btn_delete.setEnabled(true);
    }//GEN-LAST:event_table_dataSericeMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        btn_add.setEnabled(true);
        btn_delete.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        txtName.setText("");
        txtPrice.setText("");
        txtId.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_loadData;
    private javax.swing.JPanel formData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_dataSerice;
    private javax.swing.JLabel txtErrorName;
    private javax.swing.JLabel txtErrorPrice;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
