/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.internalframe;

import bkap.daoimpl.RoomDaoImpl;
import bkap.entity.Room;
import bkap.utils.Constant;
import bkap.utils.Helper;
import java.awt.Button;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ShowAllRoom extends javax.swing.JInternalFrame {
    OrderRoom_JIF orderroom;
    RoomDaoImpl roomDaoImpl;
    List<Room> ls;
    Helper helper;
    
    Callback callback;
    
    public interface Callback{
        void doAddRoomToOrderRoom(int id);
        void doAdvancedSearch();
    } 
    
    /**
     * contructor để phục vụ mục đích callback
     * 
     */
    public ShowAllRoom(Callback callback) {
        initComponents();
        loadTable(jPanelShow);
        loadData();
        this.callback = callback;
        
    }

    /**
     * Creates new form ShowAllRoom
     */
    public ShowAllRoom() {
        initComponents();
        loadTable(jPanelShow);
    }
    
    public void loadData() {
        helper = new Helper();
        helper.loadDataIntoComboBox(cboCateRoomTKALLRoom, Constant.SQL_SELECT_CATEGORYROOM, "Name");
        cboCateRoomTKALLRoom.setSelectedIndex(1);
    }
    
    public void loadTable(JPanel pnlShow) {
        roomDaoImpl =  new RoomDaoImpl();
        ls = roomDaoImpl.getAllRooms();
        for (Room l : ls) {
            
            Button btn = new Button();
            btn.setLabel(l.getName());
            pnlShow.add(btn);
            btn.setSize(20,20);
            
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   callback.doAddRoomToOrderRoom(l.getId());
                }
            });
        }
        pnlShow.setLayout(new GridLayout(3, 3, 2, 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboCateRoomTKALLRoom = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboTrangThaiTKAllRoom = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMinPrice = new javax.swing.JTextField();
        btnSearchAllRoom = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaxPrice = new javax.swing.JTextField();
        btnAdvancedSearch = new javax.swing.JButton();
        jPanelShow = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        jLabel1.setText("Danh mục phòng: ");

        cboCateRoomTKALLRoom.setName("cateShowAllRoom"); // NOI18N

        jLabel2.setText("Trạng Thái: ");

        cboTrangThaiTKAllRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Trạng Thái--", "Hiện", "Ẩn" }));

        jLabel3.setText("Giá Phòng/1 ngày: ");

        btnSearchAllRoom.setText("Tìm Kiếm");
        btnSearchAllRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllRoomActionPerformed(evt);
            }
        });

        jLabel4.setText("->");

        btnAdvancedSearch.setText("Tìm kiếm nâng cao");
        btnAdvancedSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvancedSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboCateRoomTKALLRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cboTrangThaiTKAllRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnAdvancedSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchAllRoom))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboCateRoomTKALLRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboTrangThaiTKAllRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAllRoom)
                    .addComponent(btnAdvancedSearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelShow.setBorder(javax.swing.BorderFactory.createTitledBorder("List Room"));

        javax.swing.GroupLayout jPanelShowLayout = new javax.swing.GroupLayout(jPanelShow);
        jPanelShow.setLayout(jPanelShowLayout);
        jPanelShowLayout.setHorizontalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelShowLayout.setVerticalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchAllRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllRoomActionPerformed
        // TODO add your handling code here:
        System.out.println("bkap.internalframe.ShowAllRoom.btnSearchAllRoomActionPerformed()"+"hihi");
        String nameCate = cboCateRoomTKALLRoom.getSelectedItem().toString();
        int statusId = 0;
        try {
            int cateId = (int) helper.getFieldByFieldString("category_room", "Id", "Name", nameCate);
            if(cboTrangThaiTKAllRoom.getSelectedItem().toString().equals("Hiện")) {
                statusId = 1;
            }else {
                statusId = 0;
            }
            float minPrice = Float.parseFloat(txtMinPrice.getText());
            float maxPrice = Float.parseFloat(txtMaxPrice.getText());
            roomDaoImpl =  new RoomDaoImpl();
            ls = roomDaoImpl.searchByCateStatusPrice(cateId, statusId, minPrice, maxPrice);
            System.out.println("bkap.internalframe.ShowAllRoom.btnSearchAllRoomActionPerformed()"+ls);
            System.out.println("bkap.internalframe.ShowAllRoom.btnSearchAllRoomActionPerformed()"+cateId);
            System.out.println("bkap.internalframe.ShowAllRoom.btnSearchAllRoomActionPerformed()"+statusId);
            System.out.println("bkap.internalframe.ShowAllRoom.btnSearchAllRoomActionPerformed()"+minPrice);
            System.out.println("bkap.internalframe.ShowAllRoom.btnSearchAllRoomActionPerformed()"+maxPrice);
            jPanelShow.removeAll();
            for (Room l : ls) {
                System.out.println("bkap.internalframe.ShowAllRoom.btnSearchAllRoomActionPerformed()"+l.getName());
                Button btn = new Button();
                btn.setLabel(l.getName());
                jPanelShow.add(btn);
                btn.setSize(20,20);

                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                       callback.doAddRoomToOrderRoom(l.getId());
                    }
                });
            }
            jPanelShow.setLayout(new GridLayout(3, 3, 2, 2));
        } catch (SQLException ex) {
            Logger.getLogger(ShowAllRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchAllRoomActionPerformed

    private void btnAdvancedSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvancedSearchActionPerformed
        // TODO add your handling code here:
        callback.doAdvancedSearch();
    }//GEN-LAST:event_btnAdvancedSearchActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvancedSearch;
    private javax.swing.JButton btnSearchAllRoom;
    private javax.swing.JComboBox<String> cboCateRoomTKALLRoom;
    private javax.swing.JComboBox<String> cboTrangThaiTKAllRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelShow;
    private javax.swing.JTextField txtMaxPrice;
    private javax.swing.JTextField txtMinPrice;
    // End of variables declaration//GEN-END:variables
}
